#!/usr/bin/env bash

configNameInndata=inndata-api-properties
configNameUtdata=utdata-api-properties

syntax="[d|c|r], deploy (docker), configure (properties), remove (properties)"

if [ -z "${1}" ]; then
  echo "usage: ${0} ${syntax}"
  exit 0
fi

if [ "${1}" = "d" ]; then
    echo "Deploy"

    export DOCKER_REGISTRY=local
    export DOCKER_IMAGE_VERSION=local-${RANDOM}

    mvn package \
        -Dno.difi.jenkins-pipeline.docker-registry=${DOCKER_REGISTRY} \
        -Dno.difi.jenkins-pipeline.docker-image-version=${DOCKER_IMAGE_VERSION} \
        -DskipTests || exit 1

    VERSION=${DOCKER_IMAGE_VERSION} REGISTRY=${DOCKER_REGISTRY} \
        docker stack deploy -c docker/stack.yml --prune --resolve-image=never statistics || exit 1

    echo "Deployed services using locally built image(s) with tag ${DOCKER_IMAGE_VERSION}"

    exit 0
fi

if [ "${1}" = "c" ]; then

configString="no.difi.statistics.elasticsearch.host = 7834108d7d5d491587be2a1a9452d636.northeurope.azure.elastic-cloud.com
no.difi.statistics.elasticsearch.port = 9243"

    if [ -z $(docker config ls -qf name=${configNameInndata}) ]; then
        read -p "No configuration found for ${configNameInndata}. Do you want me to create one? [Y/n] " answer
        [[ -z ${answer} ]] && answer='y'
        [[ ${answer} =~ [yY] ]] && { echo "${configString}" | docker config create ${configNameInndata} -; } || { exit 1; }
    else
        echo "Already a configuration named ${configNameInndata}"
    fi

    if [ -z $(docker config ls -qf name=${configNameUtdata}) ]; then
        read -p "No configuration found for ${configNameUtdata}. Do you want me to create one? [Y/n] " answer
        [[ -z ${answer} ]] && answer='y'
        [[ ${answer} =~ [yY] ]] && { echo "${configString}" | docker config create ${configNameUtdata} -; } || { exit 1; }
    else
        echo "Already a configuration named ${utdataConfigName}"
    fi

    exit 0
fi

if [ "${1}" = "r" ]; then
    echo "Remove docker config properties"
    [[ -z $(docker config ls -qf name=${configNameInndata}) ]] || docker config rm ${configNameInndata}
    [[ -z $(docker config ls -qf name=${configNameUtdata}) ]] || docker config rm ${configNameUtdata}
    exit 0
fi

if [ -n "${1}" ]; then
  echo "usage: ${0} ${syntax}"
  exit 0
fi
