#!/usr/bin/env bash

export VERSION=DEV-SNAPSHOT
export REGISTRY=local

mvn package -Dno.difi.jenkins-pipeline.docker-registry=$REGISTRY -DskipTests || exit 1
docker stack deploy -c docker/stack.yml --resolve-image=never statistics